### ISSUE TITLE
Support OCI images

### ISSUE THREAD

**Issue by ernado** [ten-nancy/porto#7]
Support Open Container Initiative images

https://opencontainers.org/
https://github.com/opencontainers/image-spec

```console
$ portoctl docker-pull ubuntu
Can't pull docker image: Docker:(Unknown manifest mediaType: application/vnd.oci.image.index.v1+json)
```

**Comment by kndrvt** [comment]
@ernado I added OCI mediatypes support [here](https://github.com/ten-nancy/porto/commit/92475488d354ba4af718765712139dda3751a4f9). Check it, please

**Comment by ernado** [comment]
Works now, thank you!
