### ISSUE TITLE
Option to disable NBD features

### ISSUE THREAD

**Issue by koct9i** [ten-nancy/porto#8]
Adding new optional features without feature-flag in config is a bad design descisions.

I wanna build and run this in docker container for ytsaurus testing and nbd definitely is out of scope.

**Comment by kndrvt** [comment]
Hello, thanks for issue.

We added necessary option in Porto config ([b40e4e2](https://github.com/ten-nancy/porto/commit/b40e4e2c9f5c7d013fc090d8b90f703f1f876ada)), so you can try it. We are waiting for your feedback.
